### ISSUE TITLE
Thank you - not sure how to use this

### ISSUE THREAD

**Issue by MiloBedford** [krishenriksen/AnberPorts-Keyboard-Mouse#1]
Firstly thank you for all your work. 

I think this will be the soloution to some of the in game save issues I'm having that require an alpha/nurmeric value to create the save. Duke3d is fine but I can't make it work in Shadow warrior. Aplogies for my naivety but I can't work out how to run this. I can ssh into the rg351 but just really not sure what else to type other than then the command line you provided. I also can't find the folder stucutre you mentioned for the udev rule. That said I don't really understand what this means either.. sorry. Any advice you can give me on how to activate/ install please do. 

Thanks again

**Comment by krishenriksen** [comment]
Look in AnberPorts, new and updated AnberPorts-Joystick with custom controls.
